services:
  mihomo:
    image: metacubex/mihomo:v1.19.29
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./data:/root/.config/mihomo
      - /dev/net/tun:/dev/net/tun
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      createdBy: "Apps"

  metacubexd:
    image: ghcr.io/metacubex/metacubexd:v1.273.0
    container_name: ${CONTAINER_NAME}-ui
    restart: always
    network_mode: bridge
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  1panel-network:
    external: true